Update issue templates
R0Wi/workflow_ocr pull request #189
Opened 2023-02-23 12:36 UTC by R0Wi

2023-02-23 20:02 UTC, bahnwaerter requested changes
Please take a look at my comments and try to resolve them.

2023-02-23 20:02 UTC, bahnwaerter commented on .github/ISSUE_TEMPLATE/bug_report.md
> +about: Create a report to help us improve
[...] to improve what???

```suggestion
about: Create a report to help us to improve the Nextcloud Workflow OCR app
```

2023-02-23 20:02 UTC, bahnwaerter commented on .github/ISSUE_TEMPLATE/bug_report.md
> +assignees: R0Wi
This should be a YAML list, since several assignees are possible.

2023-02-23 21:27 UTC, R0Wi commented on .github/ISSUE_TEMPLATE/bug_report.md
> +assignees: R0Wi
This was generated by Github so I expect it to work :-)

2023-02-24 07:28 UTC, bahnwaerter approved these changes
Now, the template looks good to me. Feel free to merge this change.

2023-02-24 07:41 UTC, R0Wi commented
Thx :-)

2023-02-24 07:41 UTC, merged