Add language settings and global processor settings closes #76
R0Wi/workflow_ocr pull request #85
Opened 2022-01-07 11:17 UTC by R0Wi

2022-02-04 20:30 UTC, R0Wi commented
@bahnwaerter ready for review so far. Would be happy if you could give me some feedback :rocket: 

Btw: Sonarqube seems to scan an old version of this branch and i don't know why... so let's ignore the codesmells so far

2022-02-14 23:13 UTC, bahnwaerter requested changes
I've reviewed and tested this patch. The tests have been done on a fresh Nextcloud 23.0.1 instance, where everything worked as expected.

Please take a look at the three marked code parts and resolve the annotated comments and suggestions. After that, this patch is ready for merging.

2022-02-14 23:13 UTC, bahnwaerter commented on lib/OcrProcessors/PdfOcrProcessor.php
> +
Please remove spaces at the beginning of the empty line.
```suggestion

```

2022-02-14 23:13 UTC, bahnwaerter commented on Makefile
> +	cd js && $(npm) npm run build
Do not append `npm` as parameter.
```suggestion
	cd js && $(npm) run build
```

2022-02-14 23:13 UTC, bahnwaerter commented on Makefile
> +	cd js && $(npm) npm run dev-install
Do not append `npm` as parameter.
```suggestion
	cd js && $(npm) run dev-install
```

2022-02-15 05:56 UTC, R0Wi commented on Makefile
> +	cd js && $(npm) npm run dev-install
🙈

2022-02-15 06:00 UTC, R0Wi commented
@bahnwaerter thx for feedback, did some adjustments in 834dd26a7e56641e590c12b76138e32e3c61bb09, please let me know if that works now 🚀

2022-02-15 18:32 UTC, bahnwaerter approved these changes
Now, everything seems fine. Ready for merging ...

2022-02-16 05:44 UTC, merged

2022-02-16 05:44 UTC, R0Wi commented
The backport to `stable22` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-stable22 stable22
# Navigate to the new working tree
cd .worktrees/backport-stable22
# Create a new branch
git switch --create backport-85-to-stable22
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick ---mainline 1 7d9e98f81a2d24b66aec0d2521eb3301fcc43ce1
# Push it to GitHub
git push --set-upstream origin backport-85-to-stable22
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-stable22
```
Then, create a pull request where the `base` branch is `stable22` and the `compare`/`head` branch is `backport-85-to-stable22`.

2022-02-16 05:44 UTC, R0Wi commented
The backport to `stable23` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-stable23 stable23
# Navigate to the new working tree
cd .worktrees/backport-stable23
# Create a new branch
git switch --create backport-85-to-stable23
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick ---mainline 1 7d9e98f81a2d24b66aec0d2521eb3301fcc43ce1
# Push it to GitHub
git push --set-upstream origin backport-85-to-stable23
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-stable23
```
Then, create a pull request where the `base` branch is `stable23` and the `compare`/`head` branch is `backport-85-to-stable23`.